export { apiClient, ApiError } from './client';
export { fetchCurrentRestaurant } from './restaurants.api';
export type { ApiRestaurantData } from './restaurants.api';
export { fetchMenu, adaptApiCategoriesToLocal } from './menu.api';
export type { ApiMenuItem, ApiMenuCategory, ApiMenuResponse } from './menu.api';
export { createOrder, fetchOrder } from './orders.api';
export type { CreateOrderPayload, CreateOrderResponse } from './orders.api';
export { requestOtp, verifyOtp } from './auth.api';
export type { OtpRequestPayload, OtpRequestResponse, OtpVerifyPayload, OtpVerifyResponse } from './auth.api';
export { fetchActiveGames, submitGameScore } from './games.api';
export type { ActiveGame, ActiveGamesResponse, SubmitScorePayload, SubmitScoreResponse } from './games.api';
