import type { DeliveryOrder, DeliveryPortalSnapshot } from './delivery-types';

const deliveryPortalSnapshots: Record<string, DeliveryPortalSnapshot> = {
  'mosaic-table': {
    restaurant: {
      slug: 'mosaic-table',
      name: 'Mosaic Table',
      deliveryDomain: 'mosaic-table-delivery.mydomain.com',
      zoneLabel: 'Downtown Marina and Trade Centre',
      supportPhone: '+971 50 890 2211',
    },
    agent: {
      id: 'agent-samira',
      name: 'Samira Khan',
      phone: '+971 52 880 4412',
      vehicleType: 'Scooter',
      shiftLabel: '12:00 PM to 8:00 PM',
      status: 'online',
      rating: 4.9,
      completedToday: 14,
    },
    metrics: [
      {
        label: 'Assigned now',
        value: '04',
        hint: 'Four active customer handoffs on the current route.',
        tone: 'warning',
      },
      {
        label: 'Avg route time',
        value: '19 min',
        hint: 'Healthy average for the lunch-to-evening delivery window.',
        tone: 'success',
      },
      {
        label: 'On-time rate',
        value: '96%',
        hint: 'Based on the most recent 50 completed deliveries.',
        tone: 'success',
      },
      {
        label: 'Pending handoff cash',
        value: 'AED 128',
        hint: 'Cash still expected from active cash-on-delivery stops.',
        tone: 'default',
      },
    ],
    activeOrders: [
      {
        id: 'ord-1042',
        code: 'JS-1042',
        customerName: 'Rana Elmi',
        neighborhood: 'Dubai Marina',
        dropoffAddress: 'Marina Heights Tower, Lobby B, Apartment 1604',
        orderedAtLabel: '12 minutes ago',
        etaMinutes: 11,
        itemCount: 4,
        orderValue: 'AED 72',
        paymentMode: 'prepaid',
        status: 'on_route',
        priority: 'rush',
        notes: 'Call at the lobby. Customer asked for extra napkins in the bag.',
      },
      {
        id: 'ord-1039',
        code: 'JS-1039',
        customerName: 'Yousef Rahman',
        neighborhood: 'Trade Centre',
        dropoffAddress: 'Liberty House, Office 1206, Sheikh Zayed Road',
        orderedAtLabel: '18 minutes ago',
        etaMinutes: 16,
        itemCount: 2,
        orderValue: 'AED 38',
        paymentMode: 'cash_on_delivery',
        status: 'picked_up',
        priority: 'standard',
        notes: 'Collect exact cash if possible. Reception will guide to the office tower.',
      },
      {
        id: 'ord-1037',
        code: 'JS-1037',
        customerName: 'Aaliyah Noor',
        neighborhood: 'Jumeirah Garden City',
        dropoffAddress: 'Wasl Vita, Building 3, Villa Gate 7',
        orderedAtLabel: '26 minutes ago',
        etaMinutes: 21,
        itemCount: 5,
        orderValue: 'AED 91',
        paymentMode: 'prepaid',
        status: 'assigned',
        priority: 'standard',
      },
      {
        id: 'ord-1034',
        code: 'JS-1034',
        customerName: 'Daniel George',
        neighborhood: 'Satwa',
        dropoffAddress: 'Al Diyafah Street, Building 28, Flat 203',
        orderedAtLabel: '31 minutes ago',
        etaMinutes: 9,
        itemCount: 3,
        orderValue: 'AED 56',
        paymentMode: 'cash_on_delivery',
        status: 'arrived',
        priority: 'rush',
        notes: 'Customer prefers contactless handoff at the apartment door.',
      },
    ],
    completedOrders: [
      {
        id: 'ord-1028',
        code: 'JS-1028',
        customerName: 'Fatima Kareem',
        neighborhood: 'Business Bay',
        dropoffAddress: 'Executive Tower B, Floor 9',
        orderedAtLabel: '48 minutes ago',
        etaMinutes: 0,
        itemCount: 3,
        orderValue: 'AED 64',
        paymentMode: 'prepaid',
        status: 'delivered',
        priority: 'standard',
      },
      {
        id: 'ord-1024',
        code: 'JS-1024',
        customerName: 'Leo Martin',
        neighborhood: 'Al Safa',
        dropoffAddress: 'Safa One Residences, Podium Entrance',
        orderedAtLabel: '1 hour ago',
        etaMinutes: 0,
        itemCount: 2,
        orderValue: 'AED 44',
        paymentMode: 'cash_on_delivery',
        status: 'delivered',
        priority: 'standard',
      },
    ],
    routeChecklist: [
      'Confirm every order has sealed packaging before pickup.',
      'Batch the Marina and Trade Centre stops into one route when traffic is stable.',
      'Call customers only after arriving near the building to reduce missed handoffs.',
    ],
    routeHealthLabel: 'Route health is stable with moderate traffic near Sheikh Zayed Road.',
    supportNotice:
      'The Marina cluster is moving slightly slower than forecast. Keep rush orders first and call dispatch if the route exceeds 25 minutes.',
  },
  'spice-route': {
    restaurant: {
      slug: 'spice-route',
      name: 'Spice Route Kitchen',
      deliveryDomain: 'spice-route-delivery.mydomain.com',
      zoneLabel: 'Bur Dubai and Karama',
      supportPhone: '+971 50 770 9920',
    },
    agent: {
      id: 'agent-aarav',
      name: 'Aarav Menon',
      phone: '+971 55 002 1144',
      vehicleType: 'Bike',
      shiftLabel: '2:00 PM to 10:00 PM',
      status: 'busy',
      rating: 4.8,
      completedToday: 11,
    },
    metrics: [
      {
        label: 'Assigned now',
        value: '03',
        hint: 'Current queue sized for one active courier.',
        tone: 'warning',
      },
      {
        label: 'Avg route time',
        value: '22 min',
        hint: 'Slightly elevated because of Karama evening traffic.',
        tone: 'default',
      },
      {
        label: 'On-time rate',
        value: '92%',
        hint: 'Still within target, but dispatch should watch rush orders closely.',
        tone: 'warning',
      },
      {
        label: 'Pending handoff cash',
        value: 'AED 84',
        hint: 'Two cash stops remain in the active route.',
        tone: 'default',
      },
    ],
    activeOrders: [
      {
        id: 'ord-774',
        code: 'JS-774',
        customerName: 'Imran Habib',
        neighborhood: 'Karama',
        dropoffAddress: 'Karama Center, Back Entrance, Shop 14',
        orderedAtLabel: '9 minutes ago',
        etaMinutes: 14,
        itemCount: 2,
        orderValue: 'AED 32',
        paymentMode: 'cash_on_delivery',
        status: 'picked_up',
        priority: 'rush',
      },
      {
        id: 'ord-770',
        code: 'JS-770',
        customerName: 'Sara Ahmed',
        neighborhood: 'Bur Dubai',
        dropoffAddress: 'Meena Bazaar, Building 6, Flat 802',
        orderedAtLabel: '16 minutes ago',
        etaMinutes: 19,
        itemCount: 5,
        orderValue: 'AED 86',
        paymentMode: 'prepaid',
        status: 'assigned',
        priority: 'standard',
      },
      {
        id: 'ord-768',
        code: 'JS-768',
        customerName: 'Harish Patel',
        neighborhood: 'Oud Metha',
        dropoffAddress: 'Healthcare City Residences, Tower B',
        orderedAtLabel: '28 minutes ago',
        etaMinutes: 8,
        itemCount: 3,
        orderValue: 'AED 47',
        paymentMode: 'prepaid',
        status: 'arrived',
        priority: 'rush',
      },
    ],
    completedOrders: [
      {
        id: 'ord-760',
        code: 'JS-760',
        customerName: 'Mariam Yusuf',
        neighborhood: 'Al Mankhool',
        dropoffAddress: 'Golden Sands, Building 7',
        orderedAtLabel: '43 minutes ago',
        etaMinutes: 0,
        itemCount: 4,
        orderValue: 'AED 53',
        paymentMode: 'prepaid',
        status: 'delivered',
        priority: 'standard',
      },
      {
        id: 'ord-754',
        code: 'JS-754',
        customerName: 'Rohit Das',
        neighborhood: 'Karama',
        dropoffAddress: 'Near Lulu Hypermarket, Street 17',
        orderedAtLabel: '58 minutes ago',
        etaMinutes: 0,
        itemCount: 1,
        orderValue: 'AED 18',
        paymentMode: 'cash_on_delivery',
        status: 'delivered',
        priority: 'standard',
      },
    ],
    routeChecklist: [
      'Confirm cash-on-delivery amount before leaving the restaurant.',
      'Use the Karama side streets to avoid the main market traffic buildup.',
      'Escalate to dispatch if arrival waits exceed five minutes.',
    ],
    routeHealthLabel: 'Route health is busy near Karama with mild congestion around market streets.',
    supportNotice:
      'Expect short traffic spikes during market pickup windows. Use rush stop sequencing and confirm drop-off landmarks before departure.',
  },
};

const FALLBACK_RESTAURANT_SLUG = 'mosaic-table';

export function getDeliveryPortalSnapshotBySlug(slug: string): DeliveryPortalSnapshot {
  return (
    deliveryPortalSnapshots[slug] ??
    deliveryPortalSnapshots[FALLBACK_RESTAURANT_SLUG]
  );
}

export function getDeliveryOrderById(
  slug: string,
  orderId: string
): DeliveryOrder | null {
  const snapshot = getDeliveryPortalSnapshotBySlug(slug);
  const allOrders = [...snapshot.activeOrders, ...snapshot.completedOrders];

  return allOrders.find((order) => order.id === orderId) ?? null;
}
