import { pgTable, uuid, varchar, timestamp, jsonb, boolean, integer, decimal } from 'drizzle-orm/pg-core';

export const advertisements = pgTable('advertisements', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  type: varchar('type', { length: 50 }).notNull(),          // 'platform' | 'restaurant_brought'
  mediaType: varchar('media_type', { length: 10 }).default('image').notNull(),  // 'image' | 'video' | 'gif'
  content: varchar('content', { length: 2000 }),
  imageUrl: varchar('image_url', { length: 500 }),
  linkUrl: varchar('link_url', { length: 1000 }),
  mediaUrlLow: varchar('media_url_low', { length: 500 }),
  duration: integer('duration').default(15).notNull(),
  category: varchar('category', { length: 50 }),
  budget: decimal('budget', { precision: 10, scale: 2 }).default('0'),
  costPerView3s: decimal('cost_per_view_3s', { precision: 10, scale: 2 }).default('0.30'),
  costPerViewFull: decimal('cost_per_view_full', { precision: 10, scale: 2 }).default('1.00'),
  costPerClick: decimal('cost_per_click', { precision: 10, scale: 2 }).default('5.00'),
  impressions: integer('impressions').default(0),
  spent: decimal('spent', { precision: 10, scale: 2 }).default('0'),
  totalViews3s: integer('total_views_3s').default(0),
  totalViewsFull: integer('total_views_full').default(0),
  totalClicks: integer('total_clicks').default(0),
  totalConfirmedClicks: integer('total_confirmed_clicks').default(0),
  totalAbandonedClicks: integer('total_abandoned_clicks').default(0),
  totalSkips: integer('total_skips').default(0),
  revenueJustsearch: decimal('revenue_justsearch', { precision: 10, scale: 2 }).default('0'),
  revenueRestaurant: decimal('revenue_restaurant', { precision: 10, scale: 2 }).default('0'),
  assignedGames: jsonb('assigned_games').default('[]').notNull(),
  targetRestaurants: jsonb('target_restaurants').default('[]').notNull(),
  isActive: boolean('is_active').default(true).notNull(),
  startDate: timestamp('start_date', { withTimezone: true }),
  endDate: timestamp('end_date', { withTimezone: true }),
  visibility: jsonb('visibility').default({ title: true, description: false, linkUrl: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});
