import type { Game } from '@justsearch/utils';

export const PLATFORM_GAMES: Game[] = [
  {
    id: 'vex-runner',
    name: 'Jump & Bite',
    description: 'Dash, jump, and dodge obstacles with food runners.',
    icon: '/games/vex-runner.svg',
    coverImageUrl: '/games/vex-runner.png',
    prize: 'Up to 1200 points',
    communityTopScore: 450,
    accessLevel: 'public',
    isAvailable: true,
    tag: 'HOT',
    type: 'local',
    localGameId: 'vex-runner',
  },
  {
    id: 'hungry-bird-rush',
    name: 'Hungry Bird Rush',
    description: 'Tap to fly, weave through pipes.',
    icon: '/games/vex-challenges.svg',
    coverImageUrl: '/games/hungry-bird-rush-model.png',
    prize: 'Up to 700 points',
    communityTopScore: 80,
    accessLevel: 'public',
    isAvailable: true,
    tag: 'NEW',
    type: 'local',
    localGameId: 'hungry-bird-rush',
  },
  {
    id: 'cheese-chase',
    name: 'Cheddar Chase',
    description: 'Guide the mouse through mazes collecting cheese.',
    icon: '/games/vex-6.svg',
    coverImageUrl: '/games/cheddar-chase.png',
    prize: 'Up to 2500 points',
    communityTopScore: 35,
    accessLevel: 'public',
    isAvailable: true,
    tag: 'PRO',
    type: 'local',
    localGameId: 'cheese-chase',
  },
  {
    id: 'memory-match',
    name: 'Gem Match',
    description: 'Classic card matching game.',
    icon: '/games/vex-7.svg',
    coverImageUrl: '/games/gem-match.png',
    prize: 'Up to 2000 points',
    communityTopScore: 24,
    accessLevel: 'public',
    isAvailable: true,
    tag: 'HOT',
    type: 'local',
    localGameId: 'memory-match',
  },
  {
    id: 'slice-master',
    name: 'Slice Master',
    description: 'Swipe to slice flying fruits.',
    icon: '/games/vex-8.svg',
    coverImageUrl: '/games/jump&bite.png',
    prize: 'Up to 600 points',
    communityTopScore: 90,
    accessLevel: 'public',
    isAvailable: true,
    tag: 'NEW',
    type: 'local',
    localGameId: 'slice-master',
  },
];
